-- Drop and recreate Users table (Example)

DROP TABLE IF EXISTS options CASCADE;
DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  vote_link VARCHAR(255) NOT NULL,
  result_link VARCHAR(255) NOT NULL,
  creator_id INTEGER REFERENCES users(id) DELETE ON CASCADE
);

CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  label VARCHAR(255) NOT NULL,
  points INTEGER NOT NULL,
  poll_id INTEGER REFERENCES polls(id) DELETE ON CASCADE
);
